"""E1 catalog-swap acceptance test: the navigator reads the PUBLIC catalog,
not truth.

The E1 harness generates its measurements from TRUTH star positions (what
the real sky does to the camera), but the NAVIGATOR inside it -- the
Gauss-Newton solver and the CRLB covariance -- must be fed the PUBLIC
catalog positions a real spacecraft actually carries, never the truth
positions. Today the two position sets are bitwise identical, so this
rewiring changes no committed E1 number; these three tests prove, in
executable form, (1) the navigator genuinely consumes the catalog and
would move if the catalog were wrong, (2) the catalog and truth inputs are
byte-for-byte identical today (which is WHY nothing changes), and (3)
routing the navigator through the catalog reproduces the old truth-path
result to the last bit.
"""

from pathlib import Path

import numpy as np

from experiments.e1_crlb_grid import run_cell
from galnav.nav.catalog import load_catalog as load_nav_catalog
from galnav.truth.sky import load_catalog, star_positions_au
from tests.golden_numbers import RAD_ARCSEC

CATALOG_CSV = (
    Path(__file__).resolve().parent.parent / "data" / "gaia_dr3_nav_subset.csv"
)


def _truth_stars_all():
    """Truth-side (N, 3) star positions, au -- what generates measurements."""
    return star_positions_au(load_catalog(CATALOG_CSV))


def _nav_stars_all():
    """Nav-side (N, 3) public catalog star positions, au -- what the
    navigator (solver + covariance) is allowed to know."""
    return load_nav_catalog(CATALOG_CSV)["star_pos_au"]


def test_navigator_reads_catalog_not_truth():
    # Same truth stars in both runs (so the measurements are generated by
    # identical physics), but the navigator's CATALOG has ONE star flung
    # 1000 au off one axis in the second run. If the solver and covariance
    # read the catalog -- as a real spacecraft must -- the recovered
    # position error and the CRLB MUST change. If they secretly read truth,
    # both would be untouched and this test would fail. The measurement
    # vector must stay bit-identical, proving only the navigator's input,
    # not the simulated physics, was disturbed.
    truth = _truth_stars_all()
    nav = _nav_stars_all()
    nav_bad = nav.copy()
    nav_bad[0] = nav_bad[0] + np.array([1000.0, 0.0, 0.0])  # au, one star, one axis

    kwargs = dict(n_stars=8, dist_pc=1.0, sigma_rad=1.0 / RAD_ARCSEC, n_trials=5)
    good = run_cell(truth, nav, rng=np.random.default_rng(0), **kwargs)
    bad = run_cell(truth, nav_bad, rng=np.random.default_rng(0), **kwargs)

    assert np.array_equal(good["measured"], bad["measured"])  # (a) same physics
    assert good["crlb_au"] != bad["crlb_au"]  # (b) navigator's covariance moved
    assert good["rms_au"] != bad["rms_au"]  # (b) navigator's solution moved


def test_catalog_and_truth_positions_bitwise_identical_today():
    # Documents in executable form WHY the swap changes no committed result
    # today: the public catalog and the truth positions are byte-for-byte
    # equal. The day the two inputs silently diverge (a catalog edit, a unit
    # bug, an epoch change), this fails loudly instead of drifting the E1
    # numbers unnoticed.
    assert np.array_equal(_truth_stars_all(), _nav_stars_all())


def test_swap_preserves_results_bitwise():
    # The navigator path fed the TRUTH positions explicitly vs fed the
    # CATALOG positions, same seed and same cell: byte-identical (rms, crlb).
    # No tolerance -- exact equality -- so this is a self-contained proof
    # that the rewiring is a no-op today, needing no golden constant.
    truth = _truth_stars_all()
    nav = _nav_stars_all()
    kwargs = dict(n_stars=15, dist_pc=5.0, sigma_rad=1.0 / RAD_ARCSEC, n_trials=100)
    via_truth = run_cell(truth, truth, rng=np.random.default_rng(3), **kwargs)
    via_catalog = run_cell(truth, nav, rng=np.random.default_rng(3), **kwargs)
    assert via_truth["rms_au"] == via_catalog["rms_au"]
    assert via_truth["crlb_au"] == via_catalog["crlb_au"]
