"""Acceptance tests for the closest-lattice-point (CVP) solver (Spec 8b).

AI-authored under the build-night ratification-pending pattern (see
journal/logbook.md 2026-07-16 and the ratification worksheet). Students:
read and own every assertion before ratifying.

The physics: K pulsar phase measurements pin the spacecraft's position only
up to an integer turn-count vector m, one whole turn per pulsar. The set of
positions consistent with all K combs is the ambiguity LATTICE generated by
B (see galnav/pulsar.py). Given a measured position offset t, recovering the
right turn-counts is the CLOSEST-LATTICE-POINT problem: find the integer m
whose lattice point B m sits nearest to t. This file tests the hand-coded
solver `closest_lattice_point`.

The one guarantee it must honor is the packing-radius criterion: as long as
the prior position error ||t - B m_true|| is smaller than the packing radius
rho = lambda_1 / 2 (half the shortest lattice vector), the true lattice point
B m_true is the UNIQUE closest one -- so an exact solver MUST return m_true.
Past rho, a neighbor becomes closer and the integer genuinely flips; that is
the navigation ambiguity itself, not a solver defect (T3).

Every oracle here is either integer-exact (np.array_equal, zero tolerance) or
derived golden-free from the lattice (rho from packing_radius_km, lambda_1 by
bounded enumeration). NO new tolerance and NO new golden number is introduced;
COMB_KM is read from the FROZEN tests/golden_numbers.py to build lattice (b).
"""

import numpy as np

from galnav import pulsar
from tests.golden_numbers import COMB_KM

SEED = 20260716


def _lattice_a():
    """Orthonormal sightlines, equal combs s0: the generator is s0 * I.

    Returns: (3, 3) generator B in km. The same lattice test_e5_pulsar.py's
    T5a uses -- the simplest possible geometry, where B m is just s0 times the
    integer vector, so the closest point is m rounded coordinate by coordinate.
    """
    N = np.eye(3)
    s0 = 10073.0
    return pulsar.ambiguity_lattice_generator(N, np.array([s0, s0, s0]))


def _lattice_b():
    """The real three-pulsar T5b geometry with the frozen §12 comb spacings.

    Returns: (3, 3) generator B in km. Three spread-out unit sightlines (the
    same rows as test_e5_pulsar.py's T5b) with the Crab, B1937+21, and
    J0030+0451 comb spacings from the frozen COMB_KM. This is the skewed,
    physically realistic lattice the card's criterion is asserted on.
    """
    N = np.array([[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.5, 0.5, np.sqrt(0.5)]])
    N /= np.linalg.norm(N, axis=1, keepdims=True)
    combs = np.array([COMB_KM["B0531+21"], COMB_KM["B1937+21"], COMB_KM["J0030+0451"]])
    return pulsar.ambiguity_lattice_generator(N, combs)


def test_recovers_injected_integers_on_lattice():
    """T1 (exact, golden-free): a point ON the lattice returns its integers.

    For 200 random integer turn-counts m in [-50, 50]^3, the exact lattice
    point t = (B m) has zero offset, so B m_true is trivially the closest
    point and the solver must return m bit-for-bit. Asserting np.array_equal
    (zero tolerance) on BOTH the orthonormal and the real skewed lattice
    catches any error in the B^-1 rounding, the 27-box search, or the integer
    cast: a wrong formula lands on a neighboring integer and fails exactly.
    The single-vector call fixes the shape contract -- a (3,) input must give
    back a (3,) integer array, not (1, 3) -- so downstream callers can hand in
    one offset and get one turn-count.
    """
    rng = np.random.default_rng(SEED)
    for name, B in (("orthonormal", _lattice_a()), ("T5b-real", _lattice_b())):
        m = rng.integers(-50, 51, size=(200, 3))
        t = (B @ m.T).T  # exact lattice points, shape (200, 3)
        m_hat = pulsar.closest_lattice_point(B, t)
        assert np.array_equal(m_hat, m), name
        assert np.issubdtype(m_hat.dtype, np.integer), name
        # single-target shape contract: (3,) in -> (3,) integer out
        one = pulsar.closest_lattice_point(B, t[0])
        assert one.shape == (3,), name
        assert np.issubdtype(one.dtype, np.integer), name
        assert np.array_equal(one, m[0]), name


def test_card_criterion_recovers_within_packing_radius():
    """T2 (THE CARD CRITERION, golden-free, zero tolerance): recovery < rho.

    Compass section 6: "closest-lattice-point solver recovers injected
    integers when prior < packing radius = 1/2 lambda_1(lattice)." This is the
    exhaustive proof of exactly that, on the real T5b lattice. For 2000 random
    integer turn-counts m and 2000 random unit directions u, we push the true
    lattice point off by frac * rho along u, for frac in {0.5, 0.9, 0.99,
    0.999} -- every offset strictly inside the packing radius rho. The
    uniqueness margin (a competing lattice point is at least lambda_1 - ||off||
    = rho + (rho - ||off||) > ||off|| away) makes B m_true the UNIQUE closest
    point, so the solver must recover EVERY one of the 2000 x 4 integers
    exactly. No tolerance is possible or needed: integer equality is the whole
    claim. A solver that only rounded (no 27-box refinement) would miss the
    skewed cases where B^-1 off rounds a coordinate the wrong way -- measured:
    it does land one L-inf step off here, so this test is what proves the box
    matters.
    """
    B = _lattice_b()
    rho = pulsar.packing_radius_km(B)
    rng = np.random.default_rng(SEED)
    n = 2000
    m = rng.integers(-50, 51, size=(n, 3))
    g = rng.standard_normal((n, 3))
    u = g / np.linalg.norm(g, axis=1, keepdims=True)  # unit directions
    for frac in (0.5, 0.9, 0.99, 0.999):
        t = (B @ m.T).T + frac * rho * u  # offset strictly inside rho
        m_hat = pulsar.closest_lattice_point(B, t)
        assert np.array_equal(m_hat, m), frac


def test_boundary_beyond_packing_radius_is_the_ambiguity():
    """T3 (boundary honesty, deterministic, golden-free): past rho it flips.

    This documents that rho is the PHYSICAL boundary, not a solver tuning
    knob. We take the shortest lattice vector v1 (norm lambda_1 = 2 rho, found
    by the same bounded [-2, 2]^3 enumeration shortest_vector_km uses) and push
    the true point a distance 1.5 rho = 0.75 lambda_1 straight along it. The
    neighboring lattice point B(m_true + m_v1) is then only 0.25 lambda_1 away
    -- strictly closer than the injected point at 0.75 lambda_1 -- so a CORRECT
    solver must NOT return m_true; the integer has genuinely flipped to the
    neighbor. Asserting both "not m_true" and "strictly closer than m_true"
    proves the solver honestly reports the ambiguity rather than clinging to
    the injected answer. A solver that always echoed its Babai seed, or that
    never searched neighbors, would wrongly return m_true and fail here.
    """
    B = _lattice_b()
    rho = pulsar.packing_radius_km(B)
    # shortest-vector integer coords by bounded enumeration (as shortest_vector_km)
    best_m, best_norm = None, np.inf
    for i in range(-2, 3):
        for j in range(-2, 3):
            for k in range(-2, 3):
                if i == 0 and j == 0 and k == 0:
                    continue
                norm = np.linalg.norm(B @ np.array([i, j, k], dtype=float))
                if norm < best_norm:
                    best_norm, best_m = norm, np.array([i, j, k])
    v1 = B @ best_m.astype(float)  # shortest lattice vector, ||v1|| = lambda_1
    m_true = np.array([2, -1, 3])
    t = (B @ m_true.astype(float)) + 1.5 * rho * (v1 / np.linalg.norm(v1))
    m_hat = pulsar.closest_lattice_point(B, t)
    resid_true = np.linalg.norm(B @ m_true.astype(float) - t)
    resid_hat = np.linalg.norm(B @ m_hat.astype(float) - t)
    assert not np.array_equal(m_hat, m_true)  # the integer flipped
    assert resid_hat < resid_true  # the returned point is strictly closer


def test_non_3x3_generator_raises():
    """T4 (validation): a non-3x3 generator is rejected, matching the module.

    v1 of the whole pulsar lattice is exactly K = 3 pulsars, so a generator
    that is not (3, 3) is a programming error, not a degenerate geometry. The
    solver raises ValueError the same way ambiguity_lattice_generator does,
    rather than silently computing a wrong pseudo-inverse. Both a wrong square
    size and a non-square array must be caught.
    """
    import pytest

    with pytest.raises(ValueError):
        pulsar.closest_lattice_point(np.eye(2), np.zeros(2))
    with pytest.raises(ValueError):
        pulsar.closest_lattice_point(np.ones((3, 2)), np.zeros(3))
